version: '3'
services:
  node:
    image: node:16
    container_name: bookstore-api
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    environment:
      - MONGO_USER=root
      - MONGO_PASS=supersecret_pass
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=bookstore-api
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: mongo
    container_name: bookstore_api_db
    ports:
      - 27017:27017

networks:
  default:
    name: bookstore_api_net
